image: java:8
pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - bash ./gradlew build

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
